export const QUESTION_TEMPLATES = {
  preference: [
    {
      id: 't-pref-1a',
      name: '광고 소재 A/B',
      category: '광고소재',
      description: '첫 3초 시선 집중력과 클릭 충동을 기준으로 두 소재를 비교합니다.',
      icon: '●',
      questions: [
        { id: 'p1a-q1', text: '두 소재 중 첫 3초 안에 시선을 더 강력하게 끄는 것은 무엇입니까?', type: 'radio', options: ['A', 'B'] },
        { id: 'p1a-q2', text: '선택한 소재가 귀하의 현재 필요(Needs)를 얼마나 잘 짚어냈습니까?', type: 'scale', options: [] },
        { id: 'p1a-q3', text: '선택한 소재에서 가장 매력적으로 느껴진 요소는 무엇입니까?', type: 'radio', options: ['카피라이팅', '디자인/이미지', '혜택/할인', '신뢰성'] },
        { id: 'p1a-q4', text: '두 소재 중 \'클릭해서 더 알아보기\'를 누르고 싶은 충동이 더 큰 것은 무엇입니까?', type: 'radio', options: ['A', 'B'] },
        { id: 'p1a-q5', text: '선택한 소재가 상대방 소재보다 더 끌렸던 결정적인 이유를 한 문장으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-pref-1b',
      name: '첫인상 & 전환력',
      category: '광고소재',
      description: '핵심 가치 전달 속도와 전환 가능성을 측정합니다.',
      icon: '◎',
      questions: [
        { id: 'p1b-q1', text: '두 소재 중 어떤 것이 서비스의 \'핵심 가치\'를 더 빠르고 명확하게 전달합니까?', type: 'radio', options: ['A', 'B'] },
        { id: 'p1b-q2', text: '선택한 소재가 제공하는 정보나 혜택은 얼마나 신뢰할 수 있어 보입니까?', type: 'scale', options: [] },
        { id: 'p1b-q3', text: '이 소재를 보고 났을 때 가장 기대되는 결과는 무엇입니까?', type: 'radio', options: ['시간 단축', '비용 절감', '문제 해결', '트렌드 확보'] },
        { id: 'p1b-q4', text: '두 소재 중 실제 결제나 회원가입(전환)으로 이어질 확률이 더 높은 것은 무엇입니까?', type: 'radio', options: ['A', 'B'] },
        { id: 'p1b-q5', text: '선택하지 않은 소재에서 \'이 부분은 별로다\'라고 느껴진 치명적인 이탈 포인트를 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-pref-1c',
      name: '메시지 공명 분석',
      category: '광고소재',
      description: '메시지가 타겟의 고민을 얼마나 날카롭게 찌르는지 분석합니다.',
      icon: '◆',
      questions: [
        { id: 'p1c-q1', text: '두 소재 중 귀하의 상황을 더 잘 이해하고 있다고 느껴지는 것은 무엇입니까?', type: 'radio', options: ['A', 'B'] },
        { id: 'p1c-q2', text: '메인 카피(문구)가 귀하의 평소 고민을 얼마나 날카롭게 찌르고 있습니까?', type: 'scale', options: [] },
        { id: 'p1c-q3', text: '메시지를 읽었을 때 드는 가장 강한 감정은 무엇입니까?', type: 'radio', options: ['궁금함', '강한 공감', '필요성 느낌', '무관심/거부감'] },
        { id: 'p1c-q4', text: '두 소재 중 지인이나 동료에게 추천할 만한 명분을 더 잘 제시한 것은 무엇입니까?', type: 'radio', options: ['A', 'B'] },
        { id: 'p1c-q5', text: '이 메시지가 귀하에게 더 깊게 와닿기 위해 반드시 추가되어야 할 정보가 있다면 무엇입니까?', type: 'text', options: [] },
      ],
    },
  ],

  pricing: [
    {
      id: 't-price-2a',
      name: '가격 페이지 검증',
      category: '가격',
      description: '가격 대비 가치 인식과 구매 의향을 측정합니다.',
      icon: '₩',
      questions: [
        { id: 'p2a-q1', text: '제시된 가격 대비 제공되는 서비스 가치가 합리적이라고 생각하십니까?', type: 'scale', options: [] },
        { id: 'p2a-q2', text: '가격 페이지를 처음 보았을 때 가장 먼저 든 생각은 무엇입니까?', type: 'radio', options: ['예상보다 비싸다', '합리적이다', '예상보다 저렴하다', '판단하기 어렵다'] },
        { id: 'p2a-q3', text: '결제를 망설이게 만드는 가장 큰 요인은 무엇입니까?', type: 'radio', options: ['높은 가격 부담', '불확실한 ROI', '복잡한 요금제 구성', '타사 대비 메리트 부족'] },
        { id: 'p2a-q4', text: '현재 귀하의 비즈니스 상황에서 이 가격을 지불하고 도입할 의향이 있습니까?', type: 'scale', options: [] },
        { id: 'p2a-q5', text: '이 가격에 흔쾌히 결제하기 위해 반드시 추가되어야 할 기능이나 보장이 있다면 무엇입니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-price-2b',
      name: '가격 감지 테스트',
      category: '가격',
      description: '심리적 가격 저항선과 경쟁 대비 포지셔닝을 분석합니다.',
      icon: '◎',
      questions: [
        { id: 'p2b-q1', text: '제시된 가격을 보았을 때 귀하의 심리적 저항감은 어느 정도입니까?', type: 'radio', options: ['너무 비싸서 절대 안 산다', '비싸지만 고민해본다', '예산 범위 내에 있다', '너무 싸서 품질이 의심된다'] },
        { id: 'p2b-q2', text: '이 서비스의 경쟁사 대비 가격 경쟁력은 어떻습니까?', type: 'radio', options: ['매우 우수', '우수', '보통', '열위'] },
        { id: 'p2b-q3', text: '첫 달 할인이나 프로모션이 제공된다면 즉시 결제할 의향이 있습니까?', type: 'scale', options: [] },
        { id: 'p2b-q4', text: '가격을 결정짓는 가장 중요한 요소는 무엇이라고 생각하십니까?', type: 'radio', options: ['핵심 기능의 성능', '데이터 보안/안정성', '고객 지원 속도', '브랜드 신뢰도'] },
        { id: 'p2b-q5', text: '귀하가 생각하는 이 서비스의 \'적정 월구독료\'는 얼마이며, 그 이유는 무엇입니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-price-2c',
      name: '플랜 비교 명확성',
      category: '가격',
      description: '요금제 간 차이가 직관적으로 이해되는지 측정합니다.',
      icon: '◈',
      questions: [
        { id: 'p2c-q1', text: '각 요금제 간의 기능 차이점이 명확하게 이해됩니까?', type: 'scale', options: [] },
        { id: 'p2c-q2', text: '귀하의 회사 규모에 가장 적합해 보이는 플랜은 무엇입니까?', type: 'radio', options: ['가장 저렴한 하위 플랜', '중간 플랜', '최상위 플랜', '결정하지 못함'] },
        { id: 'p2c-q3', text: '상위 플랜으로 업그레이드하고 싶게 만드는 가장 강력한 유인은 무엇입니까?', type: 'radio', options: ['핵심 기능 무제한 사용', '고급 분석/리포트 제공', '우선 지원 권한', '기타'] },
        { id: 'p2c-q4', text: '각 플랜의 명칭이 타겟 고객을 직관적으로 잘 설명하고 있습니까?', type: 'scale', options: [] },
        { id: 'p2c-q5', text: '요금제 비교 표를 보면서 가장 헷갈렸거나 이해하기 어려웠던 단어나 조건은 무엇입니까?', type: 'text', options: [] },
      ],
    },
  ],

  email: [
    {
      id: 't-email-3a',
      name: '콜드메일 효과 측정',
      category: '이메일',
      description: '이메일 Hook 강도와 전반적인 설득력을 측정합니다.',
      icon: '✉',
      questions: [
        { id: 'p3a-q1', text: '이메일의 첫 문단(Hook)이 귀하의 주의를 끄는 데 성공했습니까?', type: 'scale', options: [] },
        { id: 'p3a-q2', text: '이메일이 제안하는 핵심 가치가 귀하의 현재 업무 고민과 관련이 있습니까?', type: 'radio', options: ['매우 밀접함', '약간 관련 있음', '거의 없음', '전혀 없음'] },
        { id: 'p3a-q3', text: '이메일을 끝까지 읽고 난 후, 서비스에 대한 호기심이나 기대감이 생겼습니까?', type: 'scale', options: [] },
        { id: 'p3a-q4', text: '이메일 본문의 텍스트 분량은 읽기에 적당합니까?', type: 'radio', options: ['너무 길고 복잡하다', '적당하다', '너무 짧고 정보가 부족하다'] },
        { id: 'p3a-q5', text: '이메일을 읽고 난 후, 가장 뇌리에 남는 단어나 문장 하나는 무엇입니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-email-3b',
      name: '개봉률 최적화',
      category: '이메일',
      description: '제목줄과 미리보기 텍스트의 클릭 유인력을 분석합니다.',
      icon: '◎',
      questions: [
        { id: 'p3b-q1', text: '수신함에서 이 제목을 보았을 때, 클릭해서 열어볼 확률은 어느 정도입니까?', type: 'radio', options: ['무조건 연다', '호기심에 열어본다', '나중에 본다', '스팸으로 무시한다'] },
        { id: 'p3b-q2', text: '제목이 본문의 핵심 내용을 과장 없이 명확하게 암시하고 있습니까?', type: 'scale', options: [] },
        { id: 'p3b-q3', text: '제목에서 가장 시선을 끄는 강력한 요소는 무엇입니까?', type: 'radio', options: ['구체적인 수치/데이터', '도발적인 질문', '직관적인 혜택 제시', '개인화'] },
        { id: 'p3b-q4', text: '미리보기 텍스트(첫 문장)가 제목과 논리적으로 이어지며 본문에 대한 기대감을 높입니까?', type: 'scale', options: [] },
        { id: 'p3b-q5', text: '스팸처럼 느껴지거나 클릭을 주저하게 만든 단어/표현이 있다면 무엇입니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-email-3c',
      name: '콜드 리치아웃 효과',
      category: '이메일',
      description: '발신자 신뢰도와 CTA 명확성 및 답장 의향을 측정합니다.',
      icon: '◆',
      questions: [
        { id: 'p3c-q1', text: '이메일을 보낸 발신자에 대한 전문성과 신뢰감이 느껴집니까?', type: 'scale', options: [] },
        { id: 'p3c-q2', text: '메일에서 제안하는 오퍼(미팅, 웨비나 등)가 시간을 투자할 만큼 매력적입니까?', type: 'radio', options: ['매우 매력적이다', '평범하다', '전혀 매력적이지 않다'] },
        { id: 'p3c-q3', text: '마지막에 요구하는 행동(CTA)이 명확하고 부담스럽지 않습니까?', type: 'scale', options: [] },
        { id: 'p3c-q4', text: '실제로 이 이메일에 답장하거나 CTA 버튼을 클릭할 의향이 있습니까?', type: 'radio', options: ['예', '아니오'] },
        { id: 'p3c-q5', text: '답장이나 액션을 하지 않겠다고 결정했다면, 그 결정적인 방해 요소는 무엇입니까?', type: 'text', options: [] },
      ],
    },
  ],

  lp: [
    {
      id: 't-lp-4a',
      name: '첫인상 & 전환 신호',
      sectionLabel: '랜딩페이지 진단',
      category: '랜딩페이지',
      description: '첫 화면의 즉각적인 이해도와 CTA 클릭 충동을 검증합니다.',
      icon: '◎',
      questions: [
        { id: 'lp4a-q1', text: '이 랜딩페이지의 핵심 가치가 5초 안에 명확하게 이해됩니까?', type: 'scale', options: [] },
        { id: 'lp4a-q2', text: '첫 화면을 보고 난 후 가장 먼저 드는 감정은 무엇입니까?', type: 'radio', options: ['신뢰감', '궁금함', '무관심', '혼란스러움'] },
        { id: 'lp4a-q3', text: '메인 CTA 버튼을 클릭하고 싶은 충동이 생겼습니까?', type: 'scale', options: [] },
        { id: 'lp4a-q4', text: '이 페이지에서 가장 시선을 끄는 요소는 무엇입니까?', type: 'radio', options: ['헤드라인 카피', '비주얼/이미지', 'CTA 버튼', '혜택 목록'] },
        { id: 'lp4a-q5', text: '첫인상에서 가장 거슬리거나 신뢰를 깎아먹는 요소가 있다면 무엇입니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-lp-4b',
      name: '메시지 명확성 & 공감도',
      sectionLabel: '랜딩페이지 진단',
      category: '랜딩페이지',
      description: '핵심 카피가 타겟의 고민을 정확히 짚는지 측정합니다.',
      icon: '◆',
      questions: [
        { id: 'lp4b-q1', text: '헤드라인 카피가 귀하의 현재 상황이나 고민을 얼마나 정확히 묘사합니까?', type: 'scale', options: [] },
        { id: 'lp4b-q2', text: '이 서비스가 해결해준다고 주장하는 문제가 귀하에게 실제로 해당됩니까?', type: 'radio', options: ['매우 해당됨', '약간 해당됨', '거의 해당 안 됨', '전혀 아님'] },
        { id: 'lp4b-q3', text: '페이지를 읽고 난 후 이 제품/서비스의 핵심 차별점이 분명히 느껴집니까?', type: 'scale', options: [] },
        { id: 'lp4b-q4', text: '페이지에서 가장 공감되었던 카피나 섹션은 무엇이었습니까?', type: 'text', options: [] },
        { id: 'lp4b-q5', text: '과장되거나 신뢰를 잃게 만드는 표현이 있었습니까?', type: 'radio', options: ['예, 분명히 느껴짐', '약간 그런 부분 있음', '아니오, 전혀 없음'] },
      ],
    },
    {
      id: 't-lp-4c',
      name: '신뢰 & 전환 저해 요인',
      sectionLabel: '랜딩페이지 진단',
      category: '랜딩페이지',
      description: '소셜 프루프, 보증, 이탈 포인트를 분석합니다.',
      icon: '◈',
      questions: [
        { id: 'lp4c-q1', text: '후기, 수치, 로고 등 신뢰 요소가 구매 결정에 충분합니까?', type: 'scale', options: [] },
        { id: 'lp4c-q2', text: '가격, 환불 정책 등 결제 전 반드시 알아야 할 정보가 명확히 제시되어 있습니까?', type: 'radio', options: ['명확하다', '애매하다', '찾기 어렵다', '아예 없다'] },
        { id: 'lp4c-q3', text: '스크롤을 멈추고 이탈하고 싶어지게 만든 섹션이 있었습니까?', type: 'radio', options: ['예, 상단', '예, 중간', '예, 하단', '없었음'] },
        { id: 'lp4c-q4', text: '최종적으로 이 페이지에서 전환(가입/구매/문의)할 의향은 어느 정도입니까?', type: 'scale', options: [] },
        { id: 'lp4c-q5', text: '전환을 가로막는 가장 결정적인 장애 요소를 한 문장으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-ad-1a',
      name: 'SNS 배너 전환력 분석',
      sectionLabel: '광고 소재 진단',
      category: '랜딩페이지',
      description: 'SNS 피드에서 시선을 멈추게 하는 힘과 클릭 충동을 검증합니다.',
      icon: '📲',
      questions: [
        { id: 'ad1a-q1', text: '피드를 스크롤하다가 이 배너를 보았을 때 손가락을 멈추게 만드는 힘이 있습니까?', type: 'scale', options: [] },
        { id: 'ad1a-q2', text: '배너를 보자마자 어떤 브랜드/서비스인지 즉시 인식됩니까?', type: 'radio', options: ['1초 안에 이해됨', '3초 안에 이해됨', '5초 이상 걸림', '끝까지 모르겠음'] },
        { id: 'ad1a-q3', text: '이 배너를 클릭해서 더 알아보고 싶은 충동이 생겼습니까?', type: 'scale', options: [] },
        { id: 'ad1a-q4', text: '배너에서 시선을 가장 먼저 끄는 요소는 무엇입니까?', type: 'radio', options: ['비주얼/이미지', '헤드카피 문구', '가격/숫자 정보', '브랜드 로고'] },
        { id: 'ad1a-q5', text: '클릭하지 않겠다고 느꼈다면, 그 결정적인 이유를 한 문장으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-ad-1b',
      name: '광고 카피 공명도 테스트',
      sectionLabel: '광고 소재 진단',
      category: '랜딩페이지',
      description: '광고 헤드라인이 타겟의 고민을 얼마나 날카롭게 찌르는지 분석합니다.',
      icon: '✍',
      questions: [
        { id: 'ad1b-q1', text: '광고 카피가 귀하의 현재 업무/생활 고민을 얼마나 정확히 짚어냅니까?', type: 'scale', options: [] },
        { id: 'ad1b-q2', text: '카피를 읽고 난 후 가장 먼저 든 감정은 무엇입니까?', type: 'radio', options: ['강한 공감', '가벼운 흥미', '무관심', '거부감'] },
        { id: 'ad1b-q3', text: '메인 카피 문구 중 기억에 가장 강하게 남는 표현이 있습니까?', type: 'scale', options: [] },
        { id: 'ad1b-q4', text: '이 카피가 귀하를 "나를 위한 광고"라고 느끼게 만듭니까?', type: 'radio', options: ['완벽히 그렇다', '어느 정도 그렇다', '별로 그렇지 않다', '전혀 아니다'] },
        { id: 'ad1b-q5', text: '카피가 더 강하게 공감을 얻으려면 어떤 문구나 단어로 바꾸는 것이 좋겠습니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-ad-1c',
      name: '비주얼 & CTA 효과 검증',
      sectionLabel: '광고 소재 진단',
      category: '랜딩페이지',
      description: '비주얼 완성도·브랜드 일관성·CTA 클릭 유인력을 측정합니다.',
      icon: '🎨',
      questions: [
        { id: 'ad1c-q1', text: '광고의 비주얼(이미지/영상 썸네일)이 브랜드 이미지와 일관성이 있습니까?', type: 'scale', options: [] },
        { id: 'ad1c-q2', text: '비주얼을 보았을 때 제품/서비스의 품질이나 신뢰도가 느껴집니까?', type: 'radio', options: ['매우 그렇다', '대체로 그렇다', '보통이다', '그렇지 않다'] },
        { id: 'ad1c-q3', text: 'CTA 버튼(예: "지금 시작하기", "무료 체험") 문구가 클릭 의지를 자극합니까?', type: 'scale', options: [] },
        { id: 'ad1c-q4', text: '비주얼과 카피 중 광고의 설득력을 더 높이는 핵심 요소는 무엇이라고 생각합니까?', type: 'radio', options: ['비주얼이 압도적으로 중요', '카피가 더 중요', '둘의 조화가 핵심', '둘 다 부족하다'] },
        { id: 'ad1c-q5', text: '비주얼 또는 CTA에서 개선했으면 하는 점을 구체적으로 한 문장으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-pdp-1a',
      name: 'PDP 첫인상 & 구매 욕구',
      sectionLabel: '제품 상세 페이지 진단',
      category: '랜딩페이지',
      description: '상품 이미지·타이틀·가격의 첫 조합이 구매 충동을 얼마나 자극하는지 측정합니다.',
      icon: '🛍',
      questions: [
        { id: 'pdp1a-q1', text: '상품 메인 이미지를 처음 보았을 때 \'갖고 싶다\'는 감정이 얼마나 생겼습니까?', type: 'scale', options: [] },
        { id: 'pdp1a-q2', text: '상품명과 가격을 보고 든 첫 인상은 무엇입니까?', type: 'radio', options: ['합리적이다', '비싸 보이나 궁금하다', '가격 대비 매력이 없다', '가격 판단이 어렵다'] },
        { id: 'pdp1a-q3', text: '메인 이미지만으로 이 제품이 어떤 문제를 해결해주는지 이해됩니까?', type: 'scale', options: [] },
        { id: 'pdp1a-q4', text: '첫 화면에서 \'더 스크롤하고 싶다\'는 의욕이 생겼습니까?', type: 'radio', options: ['강하게 그렇다', '어느 정도 그렇다', '별로 그렇지 않다', '바로 이탈하고 싶었다'] },
        { id: 'pdp1a-q5', text: '첫인상에서 구매 충동을 가장 강하게 깎아내린 요소가 있다면 한 문장으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-pdp-1b',
      name: '상품 설명 설득력 & 신뢰도',
      sectionLabel: '제품 상세 페이지 진단',
      category: '랜딩페이지',
      description: '상품 설명·스펙·후기가 구매 결정을 얼마나 설득하는지 분석합니다.',
      icon: '📋',
      questions: [
        { id: 'pdp1b-q1', text: '상품 설명을 읽은 후 이 제품이 나에게 필요하다는 확신이 얼마나 생겼습니까?', type: 'scale', options: [] },
        { id: 'pdp1b-q2', text: '상품 스펙·기능 정보가 구매 판단에 충분합니까?', type: 'radio', options: ['충분하다', '조금 부족하다', '많이 부족하다', '너무 많아 오히려 복잡하다'] },
        { id: 'pdp1b-q3', text: '고객 후기나 별점이 신뢰감을 주고 구매 의향을 높입니까?', type: 'scale', options: [] },
        { id: 'pdp1b-q4', text: '설명에서 가장 설득력 있었던 요소는 무엇입니까?', type: 'radio', options: ['실제 사용 후기/리뷰', '구체적인 수치/데이터', '비포&애프터 비교', 'Q&A/FAQ 섹션'] },
        { id: 'pdp1b-q5', text: '상품 설명에서 더 보강되었으면 하는 정보나 표현을 구체적으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-pdp-1c',
      name: '이탈 포인트 & 구매 장벽',
      sectionLabel: '제품 상세 페이지 진단',
      category: '랜딩페이지',
      description: '구매를 막는 심리적·정보적 장벽과 스크롤 이탈 지점을 파악합니다.',
      icon: '🚧',
      questions: [
        { id: 'pdp1c-q1', text: '구매 버튼을 누르기 전 가장 큰 망설임의 이유는 무엇입니까?', type: 'radio', options: ['가격 부담', '품질/내구성 불확실', '배송·환불 정책 불명확', '경쟁 제품과 비교 필요'] },
        { id: 'pdp1c-q2', text: '배송 조건·환불 정책·A/S 안내가 구매 불안을 충분히 해소해 줍니까?', type: 'scale', options: [] },
        { id: 'pdp1c-q3', text: '스크롤하다가 멈추고 이탈하고 싶었던 지점이 있었습니까?', type: 'radio', options: ['없었음', '상단(이미지)', '중간(설명/스펙)', '하단(리뷰/정책)'] },
        { id: 'pdp1c-q4', text: '최종적으로 이 페이지에서 구매 버튼을 클릭할 의향은 어느 정도입니까?', type: 'scale', options: [] },
        { id: 'pdp1c-q5', text: '구매를 확정짓기 위해 반드시 추가되거나 수정되어야 할 정보가 있다면 무엇입니까?', type: 'text', options: [] },
      ],
    },
    {
      id: 't-video-1a',
      name: '도입부 3초 후킹력',
      sectionLabel: '영상/숏폼 광고 진단',
      category: '랜딩페이지',
      description: '첫 3초 이내 스킵 충동을 억제하고 시선을 붙잡는 힘을 검증합니다.',
      icon: '▶',
      questions: [
        { id: 'vid1a-q1', text: '영상의 첫 3초 이내에 \'계속 보고 싶다\'는 충동이 생겼습니까?', type: 'scale', options: [] },
        { id: 'vid1a-q2', text: '첫 장면을 보았을 때 즉각적으로 스킵하고 싶었습니까?', type: 'radio', options: ['아니오, 계속 보고 싶었다', '잠깐 보다가 넘기고 싶었다', '바로 스킵하고 싶었다'] },
        { id: 'vid1a-q3', text: '도입부에서 시선을 가장 강하게 잡은 요소는 무엇입니까?', type: 'radio', options: ['강렬한 비주얼/색감', '궁금증을 유발하는 카피', '등장인물/모델', '배경음악/효과음'] },
        { id: 'vid1a-q4', text: '썸네일(첫 프레임)이 클릭 의지를 자극합니까?', type: 'scale', options: [] },
        { id: 'vid1a-q5', text: '스킵하고 싶었다면, 그 충동이 생긴 결정적인 이유를 한 문장으로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-video-1b',
      name: '메시지 전달력 & 기억 효과',
      sectionLabel: '영상/숏폼 광고 진단',
      category: '랜딩페이지',
      description: '영상이 끝난 후 핵심 메시지가 명확하게 기억에 남는지 측정합니다.',
      icon: '🎬',
      questions: [
        { id: 'vid1b-q1', text: '영상을 끝까지 보고 난 후 이 브랜드/제품이 무엇을 파는지 명확히 이해됩니까?', type: 'scale', options: [] },
        { id: 'vid1b-q2', text: '영상에서 가장 기억에 남는 요소는 무엇입니까?', type: 'radio', options: ['핵심 카피/슬로건', '비주얼/장면', '배경음악/효과음', '등장인물의 감정 표현'] },
        { id: 'vid1b-q3', text: '영상이 전달하려는 핵심 메시지가 귀하의 상황과 얼마나 공감됩니까?', type: 'scale', options: [] },
        { id: 'vid1b-q4', text: '영상의 전체 분위기/톤이 브랜드 이미지와 잘 어울립니까?', type: 'radio', options: ['매우 잘 어울린다', '대체로 어울린다', '조금 어색하다', '전혀 어울리지 않는다'] },
        { id: 'vid1b-q5', text: '영상 중 가장 임팩트 있었던 장면이나 카피 문구를 그대로 적어주세요.', type: 'text', options: [] },
      ],
    },
    {
      id: 't-video-1c',
      name: 'CTA & 전환 의향',
      sectionLabel: '영상/숏폼 광고 진단',
      category: '랜딩페이지',
      description: '영상 말미 행동 유도의 명확성과 실제 클릭·구매 전환 의향을 측정합니다.',
      icon: '🎯',
      questions: [
        { id: 'vid1c-q1', text: '영상이 끝날 무렵 소개된 제품/서비스를 더 알아보고 싶은 의향이 생겼습니까?', type: 'scale', options: [] },
        { id: 'vid1c-q2', text: '영상의 CTA(예: "지금 구매", "링크 클릭")가 명확하고 행동하기 쉽습니까?', type: 'radio', options: ['매우 명확하다', '어느 정도 명확하다', '뭘 해야 할지 모르겠다', 'CTA가 없거나 눈에 안 띈다'] },
        { id: 'vid1c-q3', text: '광고를 본 후 실제로 구매하거나 가입·문의를 고려할 의향은 어느 정도입니까?', type: 'scale', options: [] },
        { id: 'vid1c-q4', text: '전환을 망설이게 만드는 가장 큰 이유는 무엇입니까?', type: 'radio', options: ['아직 필요성을 못 느낌', '가격 정보 부족', '브랜드 신뢰도 부족', '경쟁사 대비 메리트 불분명'] },
        { id: 'vid1c-q5', text: '이 영상이 귀하를 실제 구매로 이어지게 만들려면 무엇이 추가되거나 바뀌어야 합니까?', type: 'text', options: [] },
      ],
    },
  ],
};

export const TEMPLATE_BY_NAME = Object.fromEntries(
  Object.values(QUESTION_TEMPLATES).flat().map(t => [t.name, t])
);

export const TYPE_LABEL = { radio: '옵션형', scale: '점수형', text: '서술형' };
export const TYPE_COLOR = { radio: 'var(--blue)', scale: 'var(--accent)', text: 'var(--green)' };
